version: '3.8'

services:
  db:
    image: mysql:8
    container_name: flask_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask_db
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: flask_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_api
    ports:
      -  "8080:5000"
    environment:
      DATABASE_URL: mysql://flask_user:flask_pass@db:3306/flask_db
      FLASK_APP: app/main.py
      FLASK_ENV: development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
